CREATE TABLE IF NOT EXISTS tbl_funds (
  fund_id INT PRIMARY KEY AUTO_INCREMENT,
  fund_type VARCHAR(100) NOT NULL,
  school_name VARCHAR(255) NOT NULL,
  fund_name VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  teacher_name VARCHAR(150) NOT NULL,
  teacher_email VARCHAR(150) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  goal DECIMAL(12,2) NOT NULL,
  message TEXT,
  fund_code VARCHAR(255) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
